import { createFileRoute } from "@tanstack/react-router";
import { Bell, Clock, Heart, Home, MessageSquare, Sparkles, Target, TrendingUp, Download, Shield } from "lucide-react";
import { AppShell } from "@/components/vidya/app-shell";
import { SectionTitle, StatCard } from "@/components/vidya/ui-bits";
import { SKILL_RADAR, STORIES, WEEKLY_PROGRESS } from "@/lib/mock-data";
import { Button } from "@/components/ui/button";
import {
  Area,
  AreaChart,
  PolarAngleAxis,
  PolarGrid,
  Radar,
  RadarChart,
  ResponsiveContainer,
  Tooltip,
} from "recharts";
import { useLang } from "@/lib/lang-context";
import { useLiveStats } from "@/lib/live-data";
import { suggestHomeActivities, predictSchoolReadiness, detectWeakSkills } from "@/lib/ai-engine";

export const Route = createFileRoute("/parent")({ component: ParentDashboard });

function ParentDashboard() {
  const { t, lang } = useLang();
  const { stats } = useLiveStats();

  const NAV = [
    { to: "#overview", label: t("overview"), icon: <Home className="h-4 w-4" /> },
    { to: "#progress", label: t("progress"), icon: <TrendingUp className="h-4 w-4" /> },
    { to: "#voice-learning", label: "Voice Learning", icon: <MessageSquare className="h-4 w-4" /> },
    { to: "#activities", label: t("activities"), icon: <Heart className="h-4 w-4" /> },
  ];

  const profileSkills = { memory: 80, attention: 75, language: 85, logic: 65, math: 50, reading: 70 };
  const weakSkills = detectWeakSkills(profileSkills);
  const readiness = predictSchoolReadiness({
    name: "Aarav", age: 5, weeklyMinutes: stats.todayMinutes, streakDays: stats.streakDays, skills: profileSkills
  });
  const activities = suggestHomeActivities(profileSkills, lang);

  const AI_TIPS = weakSkills.length > 0 
    ? weakSkills.map(w => w.suggestion) 
    : ["Aarav is doing great! Keep up the daily practice."];

  const handleDownloadReport = () => {
    const reportWindow = window.open("", "_blank");
    if (!reportWindow) return;
    
    reportWindow.document.write(`
      <html>
        <head>
          <title>VidyaSetu AI Learning Report - Aarav</title>
          <style>
            body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; color: #1e293b; line-height: 1.5; }
            h1 { color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; margin-bottom: 20px; font-size: 26px; }
            .meta { background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 12px; margin-bottom: 25px; font-size: 14px; }
            .grid { display: grid; grid-template-cols: 1fr 1fr; gap: 20px; margin-bottom: 25px; }
            .card { border: 1px solid #e2e8f0; padding: 16px; border-radius: 12px; }
            .bold { font-weight: bold; color: #0f172a; }
            .section-title { font-size: 16px; font-weight: bold; color: #4f46e5; margin-bottom: 10px; }
            .footer { margin-top: 60px; text-align: center; font-size: 11px; color: #64748b; border-t: 1px solid #e2e8f0; padding-top: 15px; }
          </style>
        </head>
        <body>
          <h1>VidyaSetu AI Learning Insights</h1>
          <div class="meta">
            <p><span class="bold">Child's Name:</span> Aarav Sharma</p>
            <p><span class="bold">Age:</span> 5 Years</p>
            <p><span class="bold">Streak Active:</span> ${stats.streakDays} Days 🔥</p>
            <p><span class="bold">School Readiness Index:</span> ${readiness.score}/100 (${readiness.level})</p>
          </div>
          <div class="grid">
            <div class="card">
              <div class="section-title">Academic Strengths</div>
              <p>Aarav has shown excellent progress in Alphabet matching and shape sorting, reaching 85% language score.</p>
            </div>
            <div class="card">
              <div class="section-title">Areas for Practice</div>
              <p>Struggles slightly with numbers after 15. We suggest spending 10 minutes counting toys at home.</p>
            </div>
          </div>
          <div class="card" style="margin-bottom: 25px;">
            <div class="section-title">Speech & Pronunciation Summary</div>
            <p>Average accuracy is ${stats.speakingAccuracy || 88}%. Spoke phrases like 'Apple' and 'Ball' with correct vowels. Consonants 'M' and 'D' require minor practice.</p>
          </div>
          <div class="card">
            <div class="section-title">Home Activities Recommended by AI</div>
            <ul>
              ${activities.map(act => `<li>${act}</li>`).join("")}
            </ul>
          </div>
          <div class="footer">
            <p>Generated by VidyaSetu AI Parent Coach on ${new Date().toLocaleDateString()}</p>
          </div>
        </body>
      </html>
    `);
    reportWindow.document.close();
    // Delay slightly to allow rendering in Chrome before triggering print dialog
    setTimeout(() => {
      reportWindow.print();
    }, 500);
  };

  return (
    <AppShell role="parent" title={t("learningJourney")} nav={NAV}>
      <div id="overview" className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <StatCard icon={<Clock className="h-5 w-5" />} label={t("today")} value={`${stats.todayMinutes} min`} hint="" gradient="bg-grad-blue" />
        <StatCard icon={<TrendingUp className="h-5 w-5" />} label={t("thisWeek")} value="4h 22m" hint="7 lessons completed" gradient="bg-grad-green" delay={0.05} />
        <StatCard icon={<Target className="h-5 w-5" />} label={t("accuracy")} value="88%" hint="Above age average" gradient="bg-grad-yellow" delay={0.1} />
        <StatCard icon={<Heart className="h-5 w-5" />} label={t("happiness")} value="9.2 / 10" hint="Based on engagement" gradient="bg-grad-pink" delay={0.15} />
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-3">
        <div className="rounded-3xl border bg-card p-5 shadow-card lg:col-span-2">
          <SectionTitle title={t("learningTime")} sub={t("last7Days")} />
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={WEEKLY_PROGRESS}>
                <defs>
                  <linearGradient id="pt" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="var(--brand-green)" stopOpacity={0.5} />
                    <stop offset="100%" stopColor="var(--brand-green)" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <Tooltip contentStyle={{ background: "var(--color-card)", border: "1px solid var(--color-border)", borderRadius: 12 }} />
                <Area type="monotone" dataKey="minutes" stroke="var(--brand-green)" strokeWidth={3} fill="url(#pt)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="rounded-3xl border bg-card p-5 shadow-card">
          <SectionTitle title={t("skillRadar")} sub={t("strengthsAreas")} />
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart data={SKILL_RADAR}>
                <PolarGrid stroke="var(--color-border)" />
                <PolarAngleAxis dataKey="skill" tick={{ fill: "var(--color-muted-foreground)", fontSize: 11 }} />
                <Radar dataKey="value" stroke="var(--brand-purple)" fill="var(--brand-purple)" fillOpacity={0.35} />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-3">
        <div className="rounded-3xl bg-grad-purple p-6 text-white shadow-glow lg:col-span-2 flex flex-col justify-between">
          <div>
            <div className="mb-3 flex items-center justify-between">
              <div className="inline-flex items-center gap-2 rounded-full bg-white/20 px-3 py-1 text-xs font-bold">
                <Sparkles className="h-3 w-3" /> AI Parent Assistant
              </div>
              <div className="rounded-full bg-white/20 px-3 py-1 text-xs font-bold">
                {t("schoolReadiness")}: {readiness.score}/100 ({readiness.level})
              </div>
            </div>
            
            <h3 className="font-display text-2xl font-extrabold">{t("weeklyCoaching")}</h3>
            <p className="mt-2 text-sm opacity-90">{readiness.message}</p>
            <div className="mt-4 space-y-3">
              {AI_TIPS.map((tip, i) => (
                <div key={i} className="flex items-start gap-3 rounded-2xl bg-white/15 p-3 backdrop-blur">
                  <div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-white/25">💡</div>
                  <p className="text-sm">{tip}</p>
                </div>
              ))}
            </div>
          </div>
          <div className="flex gap-2 mt-6">
            <Button className="rounded-full bg-white text-indigo-700 hover:bg-slate-100 flex-1 font-bold">
              <MessageSquare className="mr-1.5 h-4 w-4" /> {t("askAssistant")}
            </Button>
            <Button className="rounded-full border-white/20 bg-white/10 hover:bg-white/20 text-white flex-1 font-bold" onClick={handleDownloadReport}>
              <Download className="mr-1.5 h-4 w-4" /> Export Report (PDF)
            </Button>
          </div>
        </div>

        <div className="rounded-3xl border bg-card p-5 shadow-card flex flex-col justify-between">
          <div>
            <SectionTitle title={t("recentAchievements")} />
            <div className="space-y-3 flex-1">
              <div className="flex items-center gap-3 rounded-2xl bg-muted/50 p-3">
                <div className="grid h-11 w-11 place-items-center rounded-2xl bg-grad-yellow text-2xl shadow-soft">🏆</div>
                <div className="min-w-0 flex-1">
                  <div className="truncate text-sm font-bold">{stats.streakDays}-Day Streak</div>
                  <div className="text-xs text-muted-foreground">Today</div>
                </div>
              </div>
              <div className="flex items-center gap-3 rounded-2xl bg-muted/50 p-3">
                <div className="grid h-11 w-11 place-items-center rounded-2xl bg-grad-blue text-2xl shadow-soft">🤠</div>
                <div className="min-w-0 flex-1">
                  <div className="truncate text-sm font-bold">Explorer Hat Unlocked</div>
                  <div className="text-xs text-muted-foreground">Successfully unlocked in room</div>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-auto pt-5 rounded-2xl border-2 border-dashed border-brand-orange/40 bg-brand-orange/5 p-3">
            <div className="flex items-center gap-2 text-xs font-bold text-brand-orange">
              <Bell className="h-4 w-4" /> {t("screenTime")}: {stats.todayMinutes} / 60 min
            </div>
          </div>
        </div>
      </div>

      <div id="voice-learning" className="mt-6 grid gap-4 lg:grid-cols-3">
        <div className="rounded-3xl border bg-card p-5 shadow-card lg:col-span-2">
          <SectionTitle title="Voice Learning & Reading Fluency" sub="Cumulative spoken audio and pronunciation metrics" />
          <div className="grid grid-cols-3 gap-3 mb-6">
            <div className="rounded-2xl bg-muted/40 p-3 text-center">
              <div className="text-2xl font-bold text-brand-blue">{stats.speakingAccuracy || 88}%</div>
              <div className="text-[10px] uppercase font-bold text-muted-foreground mt-1">Speaking Accuracy</div>
            </div>
            <div className="rounded-2xl bg-muted/40 p-3 text-center">
              <div className="text-2xl font-bold text-brand-purple">{stats.pronunciationScore || 84}%</div>
              <div className="text-[10px] uppercase font-bold text-muted-foreground mt-1">Pronunciation Score</div>
            </div>
            <div className="rounded-2xl bg-muted/40 p-3 text-center">
              <div className="text-2xl font-bold text-brand-green">{stats.listeningScore || 92}%</div>
              <div className="text-[10px] uppercase font-bold text-muted-foreground mt-1">Listening Score</div>
            </div>
          </div>
          
          <h4 className="text-sm font-bold text-foreground mb-2">Reading Recordings Log</h4>
          <div className="space-y-2 mb-6 max-h-[140px] overflow-y-auto pr-1">
            {stats.readingRecordings && stats.readingRecordings.length > 0 ? (
              stats.readingRecordings.map((r: any) => (
                <div key={r.id} className="flex justify-between items-center bg-muted/30 hover:bg-muted/50 p-2.5 rounded-xl text-xs">
                  <div className="min-w-0 flex-1">
                    <div className="font-bold truncate text-foreground">{r.title}</div>
                    <div className="text-muted-foreground mt-0.5">{new Date(r.date).toLocaleDateString()} · {r.durationSec}s duration</div>
                  </div>
                  <div className="shrink-0 font-extrabold text-emerald-600 bg-emerald-50 px-2.5 py-1 rounded-full ml-3">
                    Fluency: {r.fluency}%
                  </div>
                </div>
              ))
            ) : (
              <div className="text-xs text-muted-foreground text-center py-4">No reading sessions recorded yet</div>
            )}
          </div>

          <h4 className="text-sm font-bold text-foreground mb-2">Spoken Activity History</h4>
          <div className="space-y-2 max-h-[150px] overflow-y-auto pr-1">
            {stats.voiceActivityHistory && stats.voiceActivityHistory.length > 0 ? (
              stats.voiceActivityHistory.map((h: any) => (
                <div key={h.id} className="flex justify-between items-center bg-muted/30 hover:bg-muted/50 p-2.5 rounded-xl text-xs">
                  <div className="min-w-0 flex-1">
                    <div className="font-bold text-foreground truncate">Spoke: "{h.phrase}"</div>
                    <div className="text-muted-foreground mt-0.5">{new Date(h.date).toLocaleDateString()}</div>
                  </div>
                  <div className={`shrink-0 font-extrabold px-2.5 py-1 rounded-full ml-3 ${
                    h.passed ? "text-emerald-600 bg-emerald-50" : "text-amber-600 bg-amber-50"
                  }`}>
                    {h.accuracy}% {h.passed ? "✔" : "✘"}
                  </div>
                </div>
              ))
            ) : (
              <div className="text-xs text-muted-foreground text-center py-4">No spoken activities recorded yet</div>
            )}
          </div>
        </div>

        <div className="rounded-3xl border bg-card p-5 shadow-card flex flex-col justify-between">
          <div>
            <SectionTitle title="AI Voice Coaching" sub="Personalized speech analytics" />
            <div className="mt-2 space-y-3">
              <div className="rounded-2xl border border-dashed border-brand-purple/40 bg-brand-purple/5 p-3.5 text-xs text-brand-purple">
                <span className="font-bold block mb-1">📢 Pronunciation Tip</span>
                Aarav shows 94% accuracy on vowel letters (A, E, I) but occasionally drops consonants (M, D). Try rhyming word games today.
              </div>
              <div className="rounded-2xl border border-dashed border-brand-green/40 bg-brand-green/5 p-3.5 text-xs text-brand-green">
                <span className="font-bold block mb-1">📖 Fluency Suggestion</span>
                Reading aloud in Story Castle is improving Chotu's confidence. His duration average is {
                  stats.readingRecordings && stats.readingRecordings.length > 0
                    ? Math.round(stats.readingRecordings.reduce((sum: number, r: any) => sum + r.durationSec, 0) / stats.readingRecordings.length)
                    : 130
                } seconds. Support him with joint read-alongs.
              </div>
            </div>
          </div>
          <div className="mt-5 p-3 rounded-2xl bg-amber-50 border border-amber-200 text-xs text-amber-800 flex gap-2">
            <Shield className="h-4 w-4 shrink-0 text-amber-500" />
            <span>Gemini recommendations: Keep the daily 10-minute storytelling rhythm.</span>
          </div>
        </div>
      </div>

      <div id="activities" className="mt-6">
        <SectionTitle title={t("homeActivities")} sub="" />
        <div className="grid gap-4 md:grid-cols-3">
          {activities.map((act, i) => (
            <div key={i} className="group rounded-3xl border bg-card p-5 shadow-card transition hover:-translate-y-1 hover:shadow-glow flex flex-col justify-between">
              <div className="mt-3 text-sm font-medium">{act}</div>
              <Button variant="outline" className="mt-4 w-full rounded-full">{t("tryActivity")}</Button>
            </div>
          ))}
        </div>
      </div>
    </AppShell>
  );
}
